# Generated by Django 5.2 on 2025-05-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_access_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="full_name"
            ),
        ),
    ]
